QUEUE_CHECK_DELAY_SEC = 0.05
CHUNK_SIZE_SEC = 0.5

SILENCE_MIN_LEN_MSEC = 1000
SILENCE_THRESHOLD_DBFS = -16
FORCE_SPLIT_RATIO_THRESHOLD = 4.0
FORCE_SPLIT_SEC_THRESHOLD = 1.0
SPEEDUP_RATIO_THRESHOLD = 2.0
SPEEDUP_RATIOSEC_THRESHOLD = 1.0
